name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ || echo "Linting completed with warnings"

      - name: Run tests
        run: |
          # Add your test command here
          echo "No tests specified" 

  dvc:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install DVC
        run: |
          pip install dvc

      - name: Pull DVC data
        run: |
          dvc pull

      - name: Run DVC pipeline
        run: |
          dvc repro