name: Python Lint and Notebook Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ || echo "Linting completed with warnings"
      - name: Check Jupyter Notebooks
        run: |
          pip install nbformat nbconvert
          jupyter nbconvert --execute --to notebook --inplace notebooks/exploratory_data_analysis.ipynb
